version: "3.7"

services:
  hammerhead:
    image: jataware/hammerhead:latest
    command:
      - ansible-playbook
      - --vault-password-file=~/.vaultpass
      - -i
      - ./hosts.py
      - redeploy-sensei.yaml
      - --limit
      - deploy.test.t.x
      - -e
      - "sensei_image_version=${SENSEI_IMAGE_VERSION:?}"

    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:?}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:?}"
      AWS_DEFAULT_REGION: us-east-1

      dockerhub_registry_user: "${DOCKERHUB_USER:?}"
      dockerhub_registry_pass: "${DOCKERHUB_PASS:?}"

    volumes:
      - ${PWD}/id_rsa:/home/apps/.ssh/id_rsa
