name: Deploy Sensei

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Docker Publish Version
    types:
      - completed

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Version
      run: make print-version prod=y

    - name: Deploy Release
      run: make deploy prod=y
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DEPLOY_ID_RSA: ${{ secrets.DEPLOY_ID_RSA }}


