name: Deploy Sensei

on:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Version
      run: make print-version prod=y

    - name: Setup Environment
      run: |
          printf "${ID_RSA}" > id_rsa
          chmod 600 id_rsa
          pwd
          ls -la
      shell: bash
      env:
        ID_RSA: ${{secrets.DEPLOY_ID_RSA}}
      working-directory: .deploy

    - name: Deploy
      run: make deploy prod=y
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKERHUB_PASS: ${{secrets.DOCKERHUB_PASS}}
        DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    - name: Cleanup
      if: ${{ !failure() }}
      run: rm -rf id_rsa


